name: Update Commit Status Badge

on:
  push:
    branches:
      - main # or the branch you want to track

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update commit status
      run: echo "![GitHub commit activity](https://img.shields.io/github/commit-activity/m/suman-chandra-barman/suman-chandra-barman)" > status.md

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add -A
        git commit -m 'Update commit status badge'
        git push
